# Generated by Django 3.0.4 on 2020-04-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title', max_length=100)),
                ('author', models.CharField(help_text='Author', max_length=100)),
                ('genre', models.CharField(help_text='Gendre', max_length=100)),
                ('sub_genre', models.CharField(help_text='Sub Gendre', max_length=100)),
                ('page_count', models.IntegerField(help_text='Number of pages')),
                ('publisher', models.CharField(help_text='Publisher name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of magazine', max_length=100)),
                ('pages', models.IntegerField(help_text='Number of pages')),
                ('ads', models.DecimalField(decimal_places=15, max_digits=30)),
                ('category', models.CharField(help_text='Category', max_length=100)),
                ('issue', models.CharField(help_text='Issue no.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
                ('magazine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Magazine')),
            ],
        ),
    ]
