# Generated by Django 3.0.4 on 2020-04-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='catalog_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Catalog_User'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='catalog_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Catalog_User'),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
