# Generated by Django 3.0.4 on 2020-04-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200405_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sub_genre',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='ads',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='pages',
        ),
    ]
