# Generated by Django 3.0.4 on 2020-04-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200405_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Catalog_User'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='catalog_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Catalog_User'),
        ),
    ]
